ALTER TABLE classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE lessons DISABLE ROW LEVEL SECURITY;
ALTER TABLE vocabulary DISABLE ROW LEVEL SECURITY;
ALTER TABLE test_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE session_details DISABLE ROW LEVEL SECURITY;
